### ISSUE TITLE
bug: query string set incorrectly during retries

### ISSUE THREAD

**Issue by viktor-f3** [heimweh/go-pagerduty#146]
We have run into an issue when using this in the PagerDuty Terraform provider we get malformed URLs when a request with a query string is rate limited.

In our specific case it was a call to /members?offset=100 would result in /members?offset=100?offset=100 on the retry, which would cause a 400 to be returned.

Fixed by this PR: https://github.com/heimweh/go-pagerduty/pull/145

**Comment by imjaroiswebdev** [comment]
Issue solved in #145
