### ISSUE TITLE
[Enhancement] Service Extensions

### ISSUE THREAD

**Issue by DWSR** [heimweh/go-pagerduty#18]
I'd love to see support for Service Extensions in the Go SDK. This is particularly a blocker for the Terraform PD provider.

terraform-providers/terraform-provider-pagerduty#46

**Comment by heimweh** [comment]
Hi @DWSR,

thanks for opening this issue!

I've opened #19 which will add support for managing service extensions.

**Comment by heimweh** [comment]
Fixed by #19
