### ISSUE TITLE
Have some issue run the example

### ISSUE THREAD

**Issue by chenrui333** [heimweh/go-pagerduty#24]
I have some issue run the example specified in the README. 

Here is what I experienced, I tried to install the package, `go get github.com/heimweh/go-pagerduty`
And then encountered the issue:
```
$ go get github.com/heimweh/go-pagerduty
can't load package: package github.com/heimweh/go-pagerduty: no Go files in /Users/rchen/go/src/github.com/heimweh/go-pagerduty
```

Then I tried, `go get github.com/heimweh/go-pagerduty/pagerduty`, seems working. But when I tried to run the program, I have issue:
```
`main.go` import section:
import (
	"fmt"

	pagerduty "github.com/heimweh/go-pagerduty"
)

$ go run main.go
main.go:6:2: no Go files in /Users/rchen/go/src/github.com/heimweh/go-pagerduty
```

**Comment by heimweh** [comment]
Hi @chenrui333,

very sorry about this. I've now updated the README with an example that should work.
