### ISSUE TITLE
Escalation policy NumLoops cannot be reset to zero

### ISSUE THREAD

**Issue by pdecat** [heimweh/go-pagerduty#32]
Having `NumLoops` serialized as `json:"num_loops,omitempty"` prevents resetting its value to zero:

https://github.com/heimweh/go-pagerduty/blob/2c0c2f005760b2286f4833621cc9daa9e581efa3/pagerduty/escalation_policy.go#L24

**Comment by stmcallister** [comment]
Looks like this was fixed and added to the provider in [v.1.9.7](https://github.com/PagerDuty/terraform-provider-pagerduty/blob/master/CHANGELOG.md#197-may-27-2021). Closing.
