### ISSUE TITLE
escalation policies seems broken

### ISSUE THREAD

**Issue by titilambert** [heimweh/go-pagerduty#33]
Hello, I just tried to create an escalation policies with terraform and I got this error:
```
Error: POST API call to https://api.pagerduty.com/escalation_policies failed 404 Not Found. Code: 2100, Errors: <nil>, Message: Not Found
```
Reading the source code there: https://github.com/heimweh/go-pagerduty/blob/2c0c2f005760b2286f4833621cc9daa9e581efa3/pagerduty/escalation_policy.go#L89

I can see that the endpoint used is effectively `/escalation_policies`

Reading the documention there, https://api-reference.pagerduty.com/#!/Escalation_Policies/get_escalation_policies, the correct endpoint seems to be `/escalation`

Could you confirm the issue ? 
Did Pagerduty changed there api ?

Thanks for you help

**Comment by titilambert** [comment]
Sorry, My bad

**Comment by pawelkowalak** [comment]
@titilambert what was the problem? We have the same issue and can't see any reason for this behavior.

**Comment by philax** [comment]
what he said

**Comment by philax** [comment]
Guessing there's something wrong on our side, causing the 404 to "appropriately" be returned?

**Comment by netjordan** [comment]
I came across this, it's typically when you're not providing the 'type' in the target, it is defaulting to users. So if you're trying to target a schedule you'll get this error.
