### ISSUE TITLE
Is it possible to override schedules with pagerduty API?

### ISSUE THREAD

**Issue by chenrui333** [heimweh/go-pagerduty#36]
Jut curious if we can override the schedules with PagerDuty API, thanks!!

**Comment by stmcallister** [comment]
It is! The functionality is even in this library: https://github.com/heimweh/go-pagerduty/blob/aa0df2b035657020dee9af47219af541fd1cb603/pagerduty/schedule.go#L224

However, it has not made it into the Terraform Provider project just yet.

**Comment by chenrui333** [comment]
Oh, I see, no wonder I could not do it. Thanks!!

**Comment by chenrui333** [comment]
Closing the issue now, thanks @stmcallister !
